version: '3.8'

services:
  # MySQL Database
  database:
    image: mysql:8.0
    container_name: expense_tracker_db
    environment:
      MYSQL_ROOT_PASSWORD: expense_tracker_password
      MYSQL_DATABASE: expense_tracker
      MYSQL_USER: expense_user
      MYSQL_PASSWORD: expense_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./scripts/init-database.sql:/docker-entrypoint-initdb.d/init-database.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Node.js Application
  app:
    build: .
    container_name: expense_tracker_app
    environment:
      DB_HOST: database
      DB_USER: expense_user
      DB_PASSWORD: expense_password
      DB_NAME: expense_tracker
      DB_PORT: 3306
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      database:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  mysql_data:
