version: '3.8'

services:
  # MySQL Database
  database:
    image: mysql:8.0
    container_name: expense_tracker_db_dev
    environment:
      MYSQL_ROOT_PASSWORD: expense_tracker_password
      MYSQL_DATABASE: expense_tracker
      MYSQL_USER: expense_user
      MYSQL_PASSWORD: expense_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data_dev:/var/lib/mysql
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Node.js Application (Development)
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: expense_tracker_app_dev
    environment:
      DB_HOST: database
      DB_USER: expense_user
      DB_PASSWORD: expense_password
      DB_NAME: expense_tracker
      DB_PORT: 3306
      PORT: 3000
      NODE_ENV: development
    ports:
      - "3000:3000"
      - "9229:9229"  # Debug port
    depends_on:
      database:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev

volumes:
  mysql_data_dev:
